kind: ConfigMap
apiVersion: v1
metadata:
  name: eap-config
data:
  TEST_URL: 'jdbc:postgresql://dbserver:5432/dbdmo'
  TEST_USERNAME: dbuser
  TEST_DATABASE: dbdmo
  TEST_PASSWORD: dbpassword
  TEST_NONXA: 'true'
  DATASOURCES: TEST
  TEST_DRIVER: postgresql
  TEST_JNDI: 'java:/jdbc/postgresql'
  TEST_NAME: postgresql
